import tkinter as tk
root=tk.Tk()
root.geometry('100x1000')
root.title("my application")
root.config(bg='light pink')
m1=tk.Label(root,text="welcome to marriage",font=("algerian",40,"bold"))
m1.place(x=400,y=0)
m2=tk.Label(root,text="venue",font=("algerian",30,"bold"))
m2.place(x=600,y=75)
m3=tk.Label(root,text="vikas funtion hall",font=("arial",20,"bold"),bg="blue",fg="white")
m3.place(x=570,y=150)
m4=tk.Label(root,text="timings:7:30 to 9:30",font=("arial",15,"normal"))
m4.place(x=570,y=200)
m5=tk.Label(root,text="varudu : vikas(B.tech completed,Msc) ",font=("arial",15,),bg="white",fg="blue")
m5.place(x=500,y=250)
m6=tk.Label(root,text="vadhuvu : revathi(B.tech completed) ",font=("arial",15,),bg="white",fg="blue")
m6.place(x=500,y=300)
m7=tk.Label(root,text="andharu ahvanitule",font=("arial",15),bg="white",fg="red")
m7.place(x=550,y=400)
root.mainloop()
